//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barkodsatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class islem_ozet
    {
        public int id { get; set; }
        public Nullable<int> islemno { get; set; }
        public Nullable<bool> iademi { get; set; }
        public string odemesekli { get; set; }
        public Nullable<double> nakit { get; set; }
        public Nullable<double> kart { get; set; }
        public Nullable<bool> gelir { get; set; }
        public Nullable<bool> gider { get; set; }
        public Nullable<double> alisfiyat_toplam { get; set; }
        public string aciklama { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string kullanici { get; set; }
    }
}
