//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barkodsatis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class barkodlusatisEntities : DbContext
    {
        public barkodlusatisEntities()
            : base("name=barkodlusatisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<terazi> terazi { get; set; }
        public virtual DbSet<hizliurun> hizliurun { get; set; }
        public virtual DbSet<islem> islem { get; set; }
        public virtual DbSet<islem_ozet> islem_ozet { get; set; }
        public virtual DbSet<satis> satis { get; set; }
        public virtual DbSet<urungrup> urungrup { get; set; }
        public virtual DbSet<barkod> barkod { get; set; }
        public virtual DbSet<stokhareket> stokhareket { get; set; }
        public virtual DbSet<sabit> sabit { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<guvenlik> guvenlik { get; set; }
    }
}
