//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barkodsatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class satis
    {
        public int satis_id { get; set; }
        public Nullable<int> islemno { get; set; }
        public string urunadi { get; set; }
        public string barkod { get; set; }
        public string urungrup { get; set; }
        public string birim { get; set; }
        public Nullable<double> alisfiyat { get; set; }
        public Nullable<double> satisfiyat { get; set; }
        public Nullable<double> miktar { get; set; }
        public Nullable<double> toplam { get; set; }
        public Nullable<double> kdvtutari { get; set; }
        public string odeme_sekli { get; set; }
        public Nullable<bool> iade { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string kullanici { get; set; }
    }
}
